name: validate

on:
  pull_request:
  # TODO(sh): remove on push
  push:
    branches:
    - dockerize

jobs:
  publish-docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Validate
      uses: ./
